### ISSUE TITLE
Trained checkpoints

### ISSUE THREAD

**Issue by somepago** [jhgan00/image-retrieval-transformers#1]
Hi,

Thank you so much for implementing the code. I am wondering if you can share the checkpoints. 

Thanks,
Gowthami

**Comment by jhgan00** [comment]
Hi,

Currently, I don't have checkpoints for trained models. So I trained IRT<sub>R</sub> model with CUB_200_2011 dataset again and uploaded the checkpoint and the training arguments [here](https://drive.google.com/drive/u/1/folders/1GtdJLy27jpxjVwCVv2Gb3IsBedLMYrgN), and colab example [here](https://colab.research.google.com/drive/14tv3FjR6RzJ6VsUjJiqguADSIo2Z4S90#scrollTo=z73xZIu9rqhj). However, other datasets are relatively large and it takes several hours to train the model  in my environment.

I'm sorry that I can't provide you with other checkpoints. If it is okay to take a long time, it can also provide checkpoints for other datasets within a few days.

Thanks !

**Comment by somepago** [comment]
Thank you so much. This is good enough. 💯
